services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces/shortsmaker:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    command: sleep infinity
    environment:
      - LOG_LEVEL=DEBUG
      - TZ=America/Sao_Paulo
      - DATABASE_URL=postgresql://user:password@postgres:5432/shortsmaker
      - GIT_SSH_COMMAND=ssh -i /home/vscode/.ssh/lsilvpin_id_rsa
    networks:
      - app_shortsmaker-network

networks:
  app_shortsmaker-network:
    external: true
